import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import ThemeProviderComponent from "@/components/ThemeProvider";


const roboto = Roboto({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-roboto",
});
export const metadata: Metadata = {
	title: "Deploy It",
	description: "Generated by creation",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${roboto.className}  antialiased`} style={{ colorScheme: "dark" }}
			>
				<ReduxProvider>
					<ThemeProviderComponent>
						{children}
					</ThemeProviderComponent>
				</ReduxProvider>
			</body>
		</html>
	);
}
