const USE_NON_AWS_STORAGE = true

const AWS_SERVER_FILES_ENDPOINT = "__app_build_outputs/"
const NON_AWS_SERVER_FILES_ENDPOINT = "projects/"

export const BUCKET_NAME = process.env.AWS_STORAGE_BUCKET_NAME //                             FILL HERE
export const AWS_STORAGE_SERVER_URL = `https://${BUCKET_NAME}.s3.us-east-1.amazonaws.com`

export const NON_AWS_STORAGE_SERVER_URL = process.env.NON_AWS_STORAGE_SERVER_URL




export const STORAGE_SERVER_URL = USE_NON_AWS_STORAGE
	? NON_AWS_STORAGE_SERVER_URL
	: AWS_STORAGE_SERVER_URL
export const STORAGE_SERVER_FILES_ENDPOINT = `${STORAGE_SERVER_URL}/${USE_NON_AWS_STORAGE
	? NON_AWS_SERVER_FILES_ENDPOINT
	: AWS_SERVER_FILES_ENDPOINT}`
